version: '3.8'
services:
  db:
      image: mysql
      environment:
          MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
          MYSQL_DATABASE: ${MYSQL_DATABASE}
      healthcheck:
          test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
          interval: 2s
          timeout: 10s
          retries: 10
  test: 
      build: .
      environment:
          MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
          MYSQL_DATABASE: ${MYSQL_DATABASE}
          MYSQL_USER: ${MYSQL_USER}
          MYSQL_HOST: db
      command: ["npm", "run", "ci:test"]
      depends_on:
          db: 
            condition: service_healthy